services:
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - BASE_URL_API=https://apisf.${DOMAIN}
    networks:
      - shared_network
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@postgresql:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRE_DAY=${JWT_ACCESS_TOKEN_EXPIRE_DAY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ENVIRONMENT=${ENVIRONMENT}
    # Todo: Add healthcheck
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  frontend:
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://apisf.${DOMAIN}/api/v1
        - NODE_ENV=production
    networks:
      - shared_network
    depends_on:
      - backend

networks:
  shared_network:
    external: true

volumes:
  app-db-data: