"""update

Revision ID: a2af89f54409
Revises: cad0d78e220c
Create Date: 2024-12-31 11:28:34.966438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2af89f54409'
down_revision: Union[str, None] = 'cad0d78e220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tb_clients',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
    )
    op.add_column(
        'tb_clients',
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
    )
    op.create_index(
        op.f('tb_clients_created_at_idx'), 'tb_clients', ['created_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tb_clients_created_at_idx'), table_name='tb_clients')
    op.drop_column('tb_clients', 'updated_at')
    op.drop_column('tb_clients', 'created_at')
    # ### end Alembic commands ###
